name: "runners - example 1"

on:
  workflow_dispatch:

jobs:
  echoJob:
    runs-on: self-hosted
    steps:
      - name: "Display files"
        run: |
          cd ~/;
          ls;
          New-Item -Path . -Name "EmptyTextFile.txt" -ItemType "file"
