name: secrets - example 1

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World by me
        uses: lgmorand/github-action-hello@v2.0.0
        with:
          firstname: ${{ secrets.FIRST_NAME }}
