name: "variables - example 2"

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: DD/MM/YYYY
          utcOffset: "+08:00"
          
      - name: Print current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        run: echo $TIME
